[platformio]
# Baris di bawah ini memaksa PlatformIO mencari file .ino di root folder
src_dir = . 
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@3.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
