name: Compile GMpro Deauther Fixed Library

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2 # Update ke v2 lebih stabil

      - name: Install Spacehuhn Deauther SDK
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json
          arduino-cli core install deauther:esp8266 --additional-urls https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json

      - name: Install Library OLED & Json
        run: |
          # Ambil path library secara otomatis (Biar gak kena Permission Denied)
          LIB_PATH=$(arduino-cli config dump | grep 'user:' | awk '{print $2}')/libraries
          mkdir -p "$LIB_PATH"

          # Install Library buat Hardware OLED
          arduino-cli lib install "Adafruit SSD1306"
          arduino-cli lib install "Adafruit GFX Library"
          arduino-cli lib install "Adafruit BusIO"
          arduino-cli lib install "SimpleCLI"
          
          # Cek file zip ArduinoJson di repo lu
          if [ -f "ArduinoJson-5.13.5.zip" ]; then
            unzip -o ArduinoJson-5.13.5.zip -d "$LIB_PATH"
          else
            # Kalau zip gak ada, install otomatis versi 5 (karena kodingan lu pake v5)
            arduino-cli lib install "ArduinoJson"@5.13.5
          fi

      - name: Compile GMpro Firmware
        run: |
          # Pastikan file kodingan lu di repo namanya GMpro.ino
          arduino-cli compile --fqbn deauther:esp8266:generic:eesz=4M2M \
          ./GMpro.ino --output-dir ./build

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: GMpro-Deauther-Binary
          path: ./build/*.bin
