name: Compile GMpro Real Match
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP8266 SDK
        run: |
          arduino-cli core update-index --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core install esp8266:esp8266@2.7.4

      - name: Prepare Local Library
        run: |
          mkdir -p /home/runner/Arduino/libraries
          arduino-cli lib install "SimpleCLI"
          # Ekstrak zip library asli dari repo lu
          unzip -o ArduinoJson-5.13.5.zip -d /home/runner/Arduino/libraries/
          # Paksa sistem buat ngenalin nama file ArduinoJson.5.13.h
          LIB_DIR=$(find /home/runner/Arduino/libraries/ -name "src" -type d)
          echo '#include "ArduinoJson.h"' > "$LIB_DIR/ArduinoJson.5.13.h"

      - name: Compile GMpro
        run: |
          # INI KUNCINYA: Build property buat buka ijin paket deauth
          arduino-cli compile --fqbn esp8266:esp8266:nodemcuv2 \
          --build-property "compiler.cpp.extra_flags=-DEXTERNAL_WIFI_PACKET_FREEDOM" \
          GMpro.ino --output-dir ./build

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: GMpro-Real-Deauth
          path: ./build/*.bin
